<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <DebugType>full</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="DataBase\Scripts\alter\20090723_0035_initial_data.sql" />
    <EmbeddedResource Include="DataBase\Scripts\alter\20090830_1754_add_is_default.sql" />
    <EmbeddedResource Include="DataBase\Scripts\alter\20090929_2217_add_decimals.sql" />
    <EmbeddedResource Include="DataBase\Scripts\alter\20091010_1709_add_types_to_account.sql" />
    <EmbeddedResource Include="DataBase\Scripts\alter\20091014_2319_add_sort_order_to_account.sql" />
    <EmbeddedResource Include="DataBase\Scripts\alter\20091026_1456_add_is_active_to_account.sql" />
    <EmbeddedResource Include="DataBase\Scripts\alter\20091110_2228_add_more_params_to_currency.sql" />
    <EmbeddedResource Include="DataBase\Scripts\alter\20091121_0104_add_is_included_into_totals_to_account.sql" />
    <EmbeddedResource Include="DataBase\Scripts\alter\20091124_1721_add_count_to_location.sql" />
    <EmbeddedResource Include="DataBase\Scripts\alter\20091124_1824_update_count_for_locations.sql" />
    <EmbeddedResource Include="DataBase\Scripts\alter\20091125_2310_update_count_for_locations.sql" />
    <EmbeddedResource Include="DataBase\Scripts\alter\20091126_2208_add_remember_fields.sql" />
    <EmbeddedResource Include="DataBase\Scripts\alter\20091127_2106_add_payee_to_transaction.sql" />
    <EmbeddedResource Include="DataBase\Scripts\alter\20091128_1302_add_last_account_id_to_account.sql" />
    <EmbeddedResource Include="DataBase\Scripts\alter\20091128_1748_add_limit_to_account.sql" />
    <EmbeddedResource Include="DataBase\Scripts\alter\20091130_2236_add_sort_order_to_category.sql" />
    <EmbeddedResource Include="DataBase\Scripts\alter\20091210_2339_add_recur_to_budget.sql" />
    <EmbeddedResource Include="DataBase\Scripts\alter\20091224_2250_alter_recur_for_existing_budgets.sql" />
    <EmbeddedResource Include="DataBase\Scripts\alter\20091228_0048_create_currency_rate_table.sql" />
    <EmbeddedResource Include="DataBase\Scripts\alter\20100114_1153_add_credit_card_type_to_account.sql" />
    <EmbeddedResource Include="DataBase\Scripts\alter\20100114_1158_alter_accounts_types.sql" />
    <EmbeddedResource Include="DataBase\Scripts\alter\20100115_0003_update_sort_order_for_all_categories.sql" />
    <EmbeddedResource Include="DataBase\Scripts\alter\20100320_2045_add_project_to_budget.sql" />
    <EmbeddedResource Include="DataBase\Scripts\alter\20100322_2041_add_expanded_to_budget.sql" />
    <EmbeddedResource Include="DataBase\Scripts\alter\20100410_1748_add_is_template_to_transaction.sql" />
    <EmbeddedResource Include="DataBase\Scripts\alter\20100416_2329_add_template_name_to_transaction.sql" />
    <EmbeddedResource Include="DataBase\Scripts\alter\20100427_2208_add_recurrence_to_transaction.sql" />
    <EmbeddedResource Include="DataBase\Scripts\alter\20100504_0020_add_notification_options_to_transaction.sql" />
    <EmbeddedResource Include="DataBase\Scripts\alter\20100506_2129_add_status_to_transaction.sql" />
    <EmbeddedResource Include="DataBase\Scripts\alter\20100511_2253_add_delete_after_expired_attribute.sql" />
    <EmbeddedResource Include="DataBase\Scripts\alter\20100522_1311_add_include_credit_to_budget.sql" />
    <EmbeddedResource Include="DataBase\Scripts\alter\20100617_2118_add_picture_to_transaction.sql" />
    <EmbeddedResource Include="DataBase\Scripts\alter\20100721_0737_add_bill_filtering_pars_to_account.sql" />
    <EmbeddedResource Include="DataBase\Scripts\alter\20100927_2135_add_last_recurrence_to_transactions.sql" />
    <EmbeddedResource Include="DataBase\Scripts\alter\20101115_2200_add_payee_table.sql" />
    <EmbeddedResource Include="DataBase\Scripts\alter\20101118_2001_add_payee_id_to_transactions.sql" />
    <EmbeddedResource Include="DataBase\Scripts\alter\20101216_0152_add_type_to_category.sql" />
    <EmbeddedResource Include="DataBase\Scripts\alter\20110227_2112_add_ccard_closing_date.sql" />
    <EmbeddedResource Include="DataBase\Scripts\alter\20110412_0024_create_running_balance_table.sql" />
    <EmbeddedResource Include="DataBase\Scripts\alter\20110420_2316_add_split_category.sql" />
    <EmbeddedResource Include="DataBase\Scripts\alter\20110422_0051_create_split_table.sql" />
    <EmbeddedResource Include="DataBase\Scripts\alter\20110429_2323_add_parent_id_to_transactions.sql" />
    <EmbeddedResource Include="DataBase\Scripts\alter\20110903_0129_alter_template_splits.sql" />
    <EmbeddedResource Include="DataBase\Scripts\alter\20111124_2133_add_last_category_id_to_payee.sql" />
    <EmbeddedResource Include="DataBase\Scripts\alter\20111127_1941_add_symbol_format_to_currency.sql" />
    <EmbeddedResource Include="DataBase\Scripts\alter\20111215_2017_add_note_to_account.sql" />
    <EmbeddedResource Include="DataBase\Scripts\alter\20120117_20581_create_currency_exchange_rate_table.sql" />
    <EmbeddedResource Include="DataBase\Scripts\alter\20120423_alter_projects_add_is_active.sql" />
    <EmbeddedResource Include="DataBase\Scripts\alter\20120709_1956_add_last_transaction_date_to_account.sql" />
    <EmbeddedResource Include="DataBase\Scripts\alter\20120820_1725_add_needed_for_sync.sql" />
    <EmbeddedResource Include="DataBase\Scripts\alter\20120904_1420_add_original_currency_and_amount_to_transactions.sql" />
    <EmbeddedResource Include="DataBase\Scripts\alter\20120906_0128_add_original_currency_and_amount_to_transactions.sql" />
    <EmbeddedResource Include="DataBase\Scripts\alter\20130624_1725_add_needed_for_sync_attributes.sql" />
    <EmbeddedResource Include="DataBase\Scripts\alter\20130704_2309_add_account_id_to_budget.sql" />
    <EmbeddedResource Include="DataBase\Scripts\alter\20130919_1725_add_needed_for_sync_blob.sql" />
    <EmbeddedResource Include="DataBase\Scripts\alter\20131226_1725_add_index_for_flowzr.sql" />
    <EmbeddedResource Include="DataBase\Scripts\alter\20160426_2152_add_title_to_locations.sql" />
    <EmbeddedResource Include="DataBase\Scripts\alter\20160426_2205_update_locations.sql" />
    <EmbeddedResource Include="DataBase\Scripts\alter\20171020_0707_add_sms_templates.sql" />
    <EmbeddedResource Include="DataBase\Scripts\alter\20171028_0707_added_required_columns_to_smstemplates.sql" />
    <EmbeddedResource Include="DataBase\Scripts\alter\20171207_0707_added_income_column_to_smstemplates.sql" />
    <EmbeddedResource Include="DataBase\Scripts\alter\20171230_1852_alter_electronic_account_type.sql" />
    <EmbeddedResource Include="DataBase\Scripts\alter\20180117_1235_add_title_to_attributes.sql" />
    <EmbeddedResource Include="DataBase\Scripts\alter\20180301_0101_added_order_column_to_smstemplates.sql" />
    <EmbeddedResource Include="DataBase\Scripts\alter\20180301_0202_add_sort_order_to_all_entities.sql" />    
    <EmbeddedResource Include="DataBase\Scripts\alter\20241228_0500_alter_sms_template_add_payee_project.sql" />
    <EmbeddedResource Include="DataBase\Scripts\alter\20250802_0155_add_currency_number_format.sql" />
    <EmbeddedResource Include="DataBase\Scripts\alter\20260613_0251_alter_sms_template_add_description.sql" />
    <EmbeddedResource Include="DataBase\Scripts\alter\20250709_1950_account_icon_color_separator.sql" />
    <EmbeddedResource Include="DataBase\Scripts\alter\20260628_0122_add_currency_trading_currency.sql" />
    <EmbeddedResource Include="DataBase\Scripts\alter\20260711_0458_add_transaction_parent_account_id.sql" />
    <EmbeddedResource Include="DataBase\Scripts\alter\20260712_0855_recreate_transactions_parent_id_idx.sql" />
    <EmbeddedResource Include="DataBase\Scripts\alter\20260719_0330_add_is_include_into_reports_to_account.sql" />
    <EmbeddedResource Include="DataBase\Scripts\alter\20260905_0241_add_payee_locations_alias.sql" />
    <EmbeddedResource Include="DataBase\Scripts\alter\20260910_1200_add_tags_to_transactions.sql" />
    <EmbeddedResource Include="DataBase\Scripts\alter\20260910_1300_create_tag_table.sql" />
    <EmbeddedResource Include="DataBase\Scripts\create\account.sql" />
    <EmbeddedResource Include="DataBase\Scripts\create\attributes.sql" />
    <EmbeddedResource Include="DataBase\Scripts\create\budget.sql" />
    <EmbeddedResource Include="DataBase\Scripts\create\category.sql" />
    <EmbeddedResource Include="DataBase\Scripts\create\currency.sql" />
    <EmbeddedResource Include="DataBase\Scripts\create\locations.sql" />
    <EmbeddedResource Include="DataBase\Scripts\create\project.sql" />
    <EmbeddedResource Include="DataBase\Scripts\create\transaction.sql" />
    <EmbeddedResource Include="DataBase\Scripts\view\010[v_all_transactions].sql" />
    <EmbeddedResource Include="DataBase\Scripts\view\015[v_blotter_for_account_with_splits].sql" />
    <EmbeddedResource Include="DataBase\Scripts\view\020[v_blotter].sql" />
    <EmbeddedResource Include="DataBase\Scripts\view\021[v_blotter_for_account].sql" />
    <EmbeddedResource Include="DataBase\Scripts\view\022[v_blotter_flatsplits].sql" />
    <EmbeddedResource Include="DataBase\Scripts\view\030[v_category].sql" />
    <EmbeddedResource Include="DataBase\Scripts\view\035[v_category_list].sql" />
    <EmbeddedResource Include="DataBase\Scripts\view\050[v_attributes].sql" />
    <EmbeddedResource Include="DataBase\Scripts\view\060[v_report_category].sql" />
    <EmbeddedResource Include="DataBase\Scripts\view\060[v_report_sub_category].sql" />
    <EmbeddedResource Include="DataBase\Scripts\view\061[v_report_period].sql" />
    <EmbeddedResource Include="DataBase\Scripts\view\062[v_report_location].sql" />
    <EmbeddedResource Include="DataBase\Scripts\view\063[v_report_project].sql" />
    <EmbeddedResource Include="DataBase\Scripts\view\064[v_report_payee].sql" />
    <EmbeddedResource Include="DataBase\Scripts\view\081[v_currency_exchange_rate].sql" />
    <EmbeddedResource Include="DataBase\Scripts\view\080[v_transaction_attributes].sql" />
    <EmbeddedResource Include="DataBase\Scripts\view\084[v_report_transactions].sql" />
    <EmbeddedResource Include="DataBase\Scripts\view\090[v_exchange_rate].sql" />
    <EmbeddedResource Include="DataBase\Scripts\view\091[v_account].sql" />
    <EmbeddedResource Include="DataBase\Scripts\view\092[v_account_with_separator].sql" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="NLog" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="DataBase\Scripts\SQL_alter_files.Designer.cs">
      <DependentUpon>SQL_alter_files.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="DataBase\Scripts\SQL_create_files.Designer.cs">
      <DependentUpon>SQL_create_files.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="DataBase\Scripts\SQL_views_files.Designer.cs">
      <DependentUpon>SQL_views_files.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="DataBase\Scripts\SQL_alter_files.resx">
      <LastGenOutput>SQL_alter_files.Designer.cs</LastGenOutput>
      <Generator>ResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="DataBase\Scripts\SQL_create_files.resx">
      <LastGenOutput>SQL_create_files.Designer.cs</LastGenOutput>
      <Generator>ResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="DataBase\Scripts\SQL_views_files.resx">
      <LastGenOutput>SQL_views_files.Designer.cs</LastGenOutput>
      <Generator>ResXFileCodeGenerator</Generator>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>Financier.DataAccess.Tests</_Parameter1>
    </AssemblyAttribute>
      <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
        <_Parameter1>Financier.Desktop.Tests</_Parameter1>
      </AssemblyAttribute>
  </ItemGroup>
  <ItemGroup>
    <None Include="..\..\.editorconfig" Link=".editorconfig" />
  </ItemGroup>
</Project>
