<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <DebugType>full</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\.editorconfig" Link=".editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.ComponentModel.Annotations" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Financisto.DataAccess\Financisto.DataAccess.csproj" />
  </ItemGroup>

</Project>
