//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Financisto.DataAccess.DataBase.Scripts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SQL_create_files {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SQL_create_files() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Financisto.DataAccess.DataBase.Scripts.SQL_create_files", typeof(SQL_create_files).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create table if not exists account ( 
        ///	_id integer primary key autoincrement, 
        ///	title text not null, 
        ///	creation_date long not null,
        ///	currency_id integer not null,
        ///	total_amount integer not null default 0
        ///);
        ///.
        /// </summary>
        internal static string account {
            get {
                return ResourceManager.GetString("account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create table if not exists attributes (
        ///	_id integer primary key autoincrement, 
        ///	type integer not null default 1,
        ///	name text not null,
        ///	list_values text,
        ///	default_value text
        ///);
        ///
        ///create table if not exists category_attribute (
        ///	category_id integer not null,
        ///	attribute_id integer not null
        ///);
        ///
        ///create index if not exists category_attr_idx ON category_attribute (category_id);
        ///
        ///create table if not exists transaction_attribute (
        ///	transaction_id integer not null,
        ///	attribute_id integer not null,
        ///	value text
        ///);
        /// </summary>
        internal static string attributes {
            get {
                return ResourceManager.GetString("attributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create table if not exists budget ( 
        ///	_id integer primary key autoincrement,
        ///	title text,
        ///	category_id long not null,		
        ///	currency_id long not null,
        ///	amount integer not null,
        ///	include_subcategories integer not null default 1,
        ///	start_date long,
        ///	end_date long,
        ///	repeat integer
        ///);
        ///
        ///.
        /// </summary>
        internal static string budget {
            get {
                return ResourceManager.GetString("budget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create table if not exists category ( 
        ///	_id integer primary key autoincrement,
        ///	title text not null,
        ///	left integer not null default 0,
        ///	right integer not null default 0
        ///);
        ///
        ///create index if not exists category_left_idx ON category (left);.
        /// </summary>
        internal static string category {
            get {
                return ResourceManager.GetString("category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create table if not exists currency (
        ///	_id integer primary key autoincrement,
        ///	name text not null,
        ///	title text not null,
        ///	symbol text not null
        ///);
        ///	
        ///.
        /// </summary>
        internal static string currency {
            get {
                return ResourceManager.GetString("currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create table if not exists locations (
        ///	_id integer primary key autoincrement, 
        ///	name text not null,	
        ///	datetime long not null,
        ///	provider text,
        ///	accuracy float,
        ///	latitude double,
        ///	longitude double,
        ///	is_payee integer not null default 0,
        ///	resolved_address text
        ///);.
        /// </summary>
        internal static string locations {
            get {
                return ResourceManager.GetString("locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create table if not exists project ( 
        ///	_id integer primary key autoincrement,
        ///	title text
        ///);
        ///
        ///.
        /// </summary>
        internal static string project {
            get {
                return ResourceManager.GetString("project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create table if not exists transactions ( 
        ///	_id integer primary key autoincrement,
        ///	from_account_id long not null,
        ///	to_account_id long not null default 0,
        ///	category_id long not null default 0,
        ///	project_id long not null default 0,
        ///	location_id long not null default 0,
        ///	note text,
        ///	from_amount integer not null default 0,
        ///	to_amount integer not null default 0,
        ///	datetime long not null,
        ///	provider text,
        ///	accuracy float,
        ///	latitude double,
        ///	longitude double
        ///);
        /// </summary>
        internal static string transaction {
            get {
                return ResourceManager.GetString("transaction", resourceCulture);
            }
        }
    }
}
