<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Controls.DataGrid" />
    <PackageReference Include="LiveChartsCore" />
    <PackageReference Include="LiveChartsCore.SkiaSharpView" />
    <PackageReference Include="LiveChartsCore.SkiaSharpView.Avalonia" />
    <PackageReference Include="Prism.Core" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Financisto.Common\Financisto.Common.csproj" />
    <ProjectReference Include="..\Financisto.DataAccess\Financisto.DataAccess.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>Financisto.Reports.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

</Project>
