<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <DebugType>full</DebugType>
    <AssemblyName>Financisto.Reports.Tests</AssemblyName>
    <RootNamespace>Financisto.Reports.Tests</RootNamespace>
    <EnforceCodeStyleInBuild>false</EnforceCodeStyleInBuild>
    <IsTestProject>true</IsTestProject>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\..\.editorconfig" Link=".editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoFixture" />
    <PackageReference Include="AutoFixture.AutoMoq" />
    <PackageReference Include="AutoFixture.Xunit3" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Microsoft.Testing.Platform.MSBuild" />
    <PackageReference Include="Moq" />
    <PackageReference Include="StyleCop.Analyzers" Condition="'$(Configuration)'=='Debug'">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Financisto.Reports\Financisto.Reports.csproj" />
    <ProjectReference Include="..\Financisto.Tests.Common\Financisto.Tests.Common.csproj" />
  </ItemGroup>

</Project>
