//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Financisto.Common.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourcesMcc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesMcc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Financisto.Common.Localization.ResourcesMcc", typeof(ResourcesMcc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessories.
        /// </summary>
        internal static string mcc_accessories {
            get {
                return ResourceManager.GetString("mcc_accessories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounting. Audit.
        /// </summary>
        internal static string mcc_accounting_audit {
            get {
                return ResourceManager.GetString("mcc_accounting_audit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertising.
        /// </summary>
        internal static string mcc_advertising {
            get {
                return ResourceManager.GetString("mcc_advertising", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agricultural Co-operatives.
        /// </summary>
        internal static string mcc_agricultural_co_operatives {
            get {
                return ResourceManager.GetString("mcc_agricultural_co_operatives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airlines.
        /// </summary>
        internal static string mcc_airlines {
            get {
                return ResourceManager.GetString("mcc_airlines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airports.
        /// </summary>
        internal static string mcc_airports {
            get {
                return ResourceManager.GetString("mcc_airports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alcohol.
        /// </summary>
        internal static string mcc_alcohol {
            get {
                return ResourceManager.GetString("mcc_alcohol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambulance.
        /// </summary>
        internal static string mcc_ambulance {
            get {
                return ResourceManager.GetString("mcc_ambulance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antiques.
        /// </summary>
        internal static string mcc_antiques {
            get {
                return ResourceManager.GetString("mcc_antiques", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applications.
        /// </summary>
        internal static string mcc_applications {
            get {
                return ResourceManager.GetString("mcc_applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aquariums. Dolphinariums.
        /// </summary>
        internal static string mcc_aquariums_dolphinariums {
            get {
                return ResourceManager.GetString("mcc_aquariums_dolphinariums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Architects.
        /// </summary>
        internal static string mcc_architects {
            get {
                return ResourceManager.GetString("mcc_architects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сard replenishment.
        /// </summary>
        internal static string mcc_ard_replenishment {
            get {
                return ResourceManager.GetString("mcc_ard_replenishment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Art goods.
        /// </summary>
        internal static string mcc_art_goods {
            get {
                return ResourceManager.GetString("mcc_art_goods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сashier&apos;s office.
        /// </summary>
        internal static string mcc_ashier_s_office {
            get {
                return ResourceManager.GetString("mcc_ashier_s_office", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сashing.
        /// </summary>
        internal static string mcc_ashing {
            get {
                return ResourceManager.GetString("mcc_ashing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atelier.
        /// </summary>
        internal static string mcc_atelier {
            get {
                return ResourceManager.GetString("mcc_atelier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Parts.
        /// </summary>
        internal static string mcc_auto_parts {
            get {
                return ResourceManager.GetString("mcc_auto_parts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto repair.
        /// </summary>
        internal static string mcc_auto_repair {
            get {
                return ResourceManager.GetString("mcc_auto_repair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto shops.
        /// </summary>
        internal static string mcc_auto_shops {
            get {
                return ResourceManager.GetString("mcc_auto_shops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autoclub.
        /// </summary>
        internal static string mcc_autoclub {
            get {
                return ResourceManager.GetString("mcc_autoclub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baby clothes.
        /// </summary>
        internal static string mcc_baby_clothes {
            get {
                return ResourceManager.GetString("mcc_baby_clothes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Babysitters.
        /// </summary>
        internal static string mcc_babysitters {
            get {
                return ResourceManager.GetString("mcc_babysitters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bakeries.
        /// </summary>
        internal static string mcc_bakeries {
            get {
                return ResourceManager.GetString("mcc_bakeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banks.
        /// </summary>
        internal static string mcc_banks {
            get {
                return ResourceManager.GetString("mcc_banks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bars.
        /// </summary>
        internal static string mcc_bars {
            get {
                return ResourceManager.GetString("mcc_bars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bicycles.
        /// </summary>
        internal static string mcc_bicycles {
            get {
                return ResourceManager.GetString("mcc_bicycles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billiard.
        /// </summary>
        internal static string mcc_billiard {
            get {
                return ResourceManager.GetString("mcc_billiard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boat Rentals.
        /// </summary>
        internal static string mcc_boat_rentals {
            get {
                return ResourceManager.GetString("mcc_boat_rentals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boats.
        /// </summary>
        internal static string mcc_boats {
            get {
                return ResourceManager.GetString("mcc_boats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonds.
        /// </summary>
        internal static string mcc_bonds {
            get {
                return ResourceManager.GetString("mcc_bonds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Stores.
        /// </summary>
        internal static string mcc_book_stores {
            get {
                return ResourceManager.GetString("mcc_book_stores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books. Press.
        /// </summary>
        internal static string mcc_books_press {
            get {
                return ResourceManager.GetString("mcc_books_press", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bowling clubs.
        /// </summary>
        internal static string mcc_bowling_clubs {
            get {
                return ResourceManager.GetString("mcc_bowling_clubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building materials.
        /// </summary>
        internal static string mcc_building_materials {
            get {
                return ResourceManager.GetString("mcc_building_materials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Services.
        /// </summary>
        internal static string mcc_business_services {
            get {
                return ResourceManager.GetString("mcc_business_services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cafe. Restaurants.
        /// </summary>
        internal static string mcc_cafe_restaurants {
            get {
                return ResourceManager.GetString("mcc_cafe_restaurants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campgrounds.
        /// </summary>
        internal static string mcc_campgrounds {
            get {
                return ResourceManager.GetString("mcc_campgrounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car dealerships.
        /// </summary>
        internal static string mcc_car_dealerships {
            get {
                return ResourceManager.GetString("mcc_car_dealerships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car dump.
        /// </summary>
        internal static string mcc_car_dump {
            get {
                return ResourceManager.GetString("mcc_car_dump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car paints.
        /// </summary>
        internal static string mcc_car_paints {
            get {
                return ResourceManager.GetString("mcc_car_paints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car rent.
        /// </summary>
        internal static string mcc_car_rent {
            get {
                return ResourceManager.GetString("mcc_car_rent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Washes.
        /// </summary>
        internal static string mcc_car_washes {
            get {
                return ResourceManager.GetString("mcc_car_washes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caregiver / Nurse.
        /// </summary>
        internal static string mcc_caregiver_nurse {
            get {
                return ResourceManager.GetString("mcc_caregiver_nurse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carpentry Contractors.
        /// </summary>
        internal static string mcc_carpentry_contractors {
            get {
                return ResourceManager.GetString("mcc_carpentry_contractors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cashback.
        /// </summary>
        internal static string mcc_cashback {
            get {
                return ResourceManager.GetString("mcc_cashback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caterers.
        /// </summary>
        internal static string mcc_caterers {
            get {
                return ResourceManager.GetString("mcc_caterers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Champagne producers.
        /// </summary>
        internal static string mcc_champagne_producers {
            get {
                return ResourceManager.GetString("mcc_champagne_producers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chancery.
        /// </summary>
        internal static string mcc_chancery {
            get {
                return ResourceManager.GetString("mcc_chancery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charging stations.
        /// </summary>
        internal static string mcc_charging_stations {
            get {
                return ResourceManager.GetString("mcc_charging_stations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charity.
        /// </summary>
        internal static string mcc_charity {
            get {
                return ResourceManager.GetString("mcc_charity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chemicals.
        /// </summary>
        internal static string mcc_chemicals {
            get {
                return ResourceManager.GetString("mcc_chemicals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiropractors.
        /// </summary>
        internal static string mcc_chiropractors {
            get {
                return ResourceManager.GetString("mcc_chiropractors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Church shops.
        /// </summary>
        internal static string mcc_church_shops {
            get {
                return ResourceManager.GetString("mcc_church_shops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cinemas.
        /// </summary>
        internal static string mcc_cinemas {
            get {
                return ResourceManager.GetString("mcc_cinemas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaning.
        /// </summary>
        internal static string mcc_cleaning {
            get {
                return ResourceManager.GetString("mcc_cleaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaning and maintenance.
        /// </summary>
        internal static string mcc_cleaning_and_maintenance {
            get {
                return ResourceManager.GetString("mcc_cleaning_and_maintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clock.
        /// </summary>
        internal static string mcc_clock {
            get {
                return ResourceManager.GetString("mcc_clock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clothes.
        /// </summary>
        internal static string mcc_clothes {
            get {
                return ResourceManager.GetString("mcc_clothes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clothing.
        /// </summary>
        internal static string mcc_clothing {
            get {
                return ResourceManager.GetString("mcc_clothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clothing rental.
        /// </summary>
        internal static string mcc_clothing_rental {
            get {
                return ResourceManager.GetString("mcc_clothing_rental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clothing repair.
        /// </summary>
        internal static string mcc_clothing_repair {
            get {
                return ResourceManager.GetString("mcc_clothing_repair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clothing stores.
        /// </summary>
        internal static string mcc_clothing_stores {
            get {
                return ResourceManager.GetString("mcc_clothing_stores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection agencies.
        /// </summary>
        internal static string mcc_collection_agencies {
            get {
                return ResourceManager.GetString("mcc_collection_agencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer Repair.
        /// </summary>
        internal static string mcc_computer_repair {
            get {
                return ResourceManager.GetString("mcc_computer_repair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer Software.
        /// </summary>
        internal static string mcc_computer_software {
            get {
                return ResourceManager.GetString("mcc_computer_software", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computers and software.
        /// </summary>
        internal static string mcc_computers_and_software {
            get {
                return ResourceManager.GetString("mcc_computers_and_software", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concrete Work Contractors.
        /// </summary>
        internal static string mcc_concrete_work_contractors {
            get {
                return ResourceManager.GetString("mcc_concrete_work_contractors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultation.
        /// </summary>
        internal static string mcc_consultation {
            get {
                return ResourceManager.GetString("mcc_consultation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consulting, PR.
        /// </summary>
        internal static string mcc_consulting_pr {
            get {
                return ResourceManager.GetString("mcc_consulting_pr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy centers.
        /// </summary>
        internal static string mcc_copy_centers {
            get {
                return ResourceManager.GetString("mcc_copy_centers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cosmetics.
        /// </summary>
        internal static string mcc_cosmetics {
            get {
                return ResourceManager.GetString("mcc_cosmetics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Court.
        /// </summary>
        internal static string mcc_court {
            get {
                return ResourceManager.GetString("mcc_court", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit bureaus.
        /// </summary>
        internal static string mcc_credit_bureaus {
            get {
                return ResourceManager.GetString("mcc_credit_bureaus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cruise Lines.
        /// </summary>
        internal static string mcc_cruise_lines {
            get {
                return ResourceManager.GetString("mcc_cruise_lines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crystal / glassware.
        /// </summary>
        internal static string mcc_crystal_glassware {
            get {
                return ResourceManager.GetString("mcc_crystal_glassware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curtains.
        /// </summary>
        internal static string mcc_curtains {
            get {
                return ResourceManager.GetString("mcc_curtains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dance studios. Dance schools.
        /// </summary>
        internal static string mcc_dance_studios_dance_schools {
            get {
                return ResourceManager.GetString("mcc_dance_studios_dance_schools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dating. Escort.
        /// </summary>
        internal static string mcc_dating_escort {
            get {
                return ResourceManager.GetString("mcc_dating_escort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery service.
        /// </summary>
        internal static string mcc_delivery_service {
            get {
                return ResourceManager.GetString("mcc_delivery_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dentistry.
        /// </summary>
        internal static string mcc_dentistry {
            get {
                return ResourceManager.GetString("mcc_dentistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department stores.
        /// </summary>
        internal static string mcc_department_stores {
            get {
                return ResourceManager.GetString("mcc_department_stores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detective agencies.
        /// </summary>
        internal static string mcc_detective_agencies {
            get {
                return ResourceManager.GetString("mcc_detective_agencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Goods.
        /// </summary>
        internal static string mcc_digital_goods {
            get {
                return ResourceManager.GetString("mcc_digital_goods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discounters.
        /// </summary>
        internal static string mcc_discounters {
            get {
                return ResourceManager.GetString("mcc_discounters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disinfecting.
        /// </summary>
        internal static string mcc_disinfecting {
            get {
                return ResourceManager.GetString("mcc_disinfecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document flow.
        /// </summary>
        internal static string mcc_document_flow {
            get {
                return ResourceManager.GetString("mcc_document_flow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drug Stores.
        /// </summary>
        internal static string mcc_drug_stores {
            get {
                return ResourceManager.GetString("mcc_drug_stores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drugs.
        /// </summary>
        internal static string mcc_drugs {
            get {
                return ResourceManager.GetString("mcc_drugs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dry Cleaners.
        /// </summary>
        internal static string mcc_dry_cleaners {
            get {
                return ResourceManager.GetString("mcc_dry_cleaners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duty Free.
        /// </summary>
        internal static string mcc_duty_free {
            get {
                return ResourceManager.GetString("mcc_duty_free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education.
        /// </summary>
        internal static string mcc_education {
            get {
                return ResourceManager.GetString("mcc_education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education. Business.
        /// </summary>
        internal static string mcc_education_business {
            get {
                return ResourceManager.GetString("mcc_education_business", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education. University.
        /// </summary>
        internal static string mcc_education_university {
            get {
                return ResourceManager.GetString("mcc_education_university", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electrical Contractors.
        /// </summary>
        internal static string mcc_electrical_contractors {
            get {
                return ResourceManager.GetString("mcc_electrical_contractors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electronics.
        /// </summary>
        internal static string mcc_electronics {
            get {
                return ResourceManager.GetString("mcc_electronics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency services.
        /// </summary>
        internal static string mcc_emergency_services {
            get {
                return ResourceManager.GetString("mcc_emergency_services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employment.
        /// </summary>
        internal static string mcc_employment {
            get {
                return ResourceManager.GetString("mcc_employment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entertainment.
        /// </summary>
        internal static string mcc_entertainment {
            get {
                return ResourceManager.GetString("mcc_entertainment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entertainment and sport.
        /// </summary>
        internal static string mcc_entertainment_and_sport {
            get {
                return ResourceManager.GetString("mcc_entertainment_and_sport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment.
        /// </summary>
        internal static string mcc_equipment {
            get {
                return ResourceManager.GetString("mcc_equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment rental.
        /// </summary>
        internal static string mcc_equipment_rental {
            get {
                return ResourceManager.GetString("mcc_equipment_rental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escort.
        /// </summary>
        internal static string mcc_escort {
            get {
                return ResourceManager.GetString("mcc_escort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farm goods.
        /// </summary>
        internal static string mcc_farm_goods {
            get {
                return ResourceManager.GetString("mcc_farm_goods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast Food.
        /// </summary>
        internal static string mcc_fast_food {
            get {
                return ResourceManager.GetString("mcc_fast_food", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial services.
        /// </summary>
        internal static string mcc_financial_services {
            get {
                return ResourceManager.GetString("mcc_financial_services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fines.
        /// </summary>
        internal static string mcc_fines {
            get {
                return ResourceManager.GetString("mcc_fines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fireplaces.
        /// </summary>
        internal static string mcc_fireplaces {
            get {
                return ResourceManager.GetString("mcc_fireplaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor coverings.
        /// </summary>
        internal static string mcc_floor_coverings {
            get {
                return ResourceManager.GetString("mcc_floor_coverings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Florists.
        /// </summary>
        internal static string mcc_florists {
            get {
                return ResourceManager.GetString("mcc_florists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flowers.
        /// </summary>
        internal static string mcc_flowers {
            get {
                return ResourceManager.GetString("mcc_flowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food stores.
        /// </summary>
        internal static string mcc_food_stores {
            get {
                return ResourceManager.GetString("mcc_food_stores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Footwear.
        /// </summary>
        internal static string mcc_footwear {
            get {
                return ResourceManager.GetString("mcc_footwear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel.
        /// </summary>
        internal static string mcc_fuel {
            get {
                return ResourceManager.GetString("mcc_fuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funeral services.
        /// </summary>
        internal static string mcc_funeral_services {
            get {
                return ResourceManager.GetString("mcc_funeral_services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fur.
        /// </summary>
        internal static string mcc_fur {
            get {
                return ResourceManager.GetString("mcc_fur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Furniture.
        /// </summary>
        internal static string mcc_furniture {
            get {
                return ResourceManager.GetString("mcc_furniture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Furniture repair.
        /// </summary>
        internal static string mcc_furniture_repair {
            get {
                return ResourceManager.GetString("mcc_furniture_repair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galleries.
        /// </summary>
        internal static string mcc_galleries {
            get {
                return ResourceManager.GetString("mcc_galleries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gambling.
        /// </summary>
        internal static string mcc_gambling {
            get {
                return ResourceManager.GetString("mcc_gambling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games.
        /// </summary>
        internal static string mcc_games {
            get {
                return ResourceManager.GetString("mcc_games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garden accessories.
        /// </summary>
        internal static string mcc_garden_accessories {
            get {
                return ResourceManager.GetString("mcc_garden_accessories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gas sales.
        /// </summary>
        internal static string mcc_gas_sales {
            get {
                return ResourceManager.GetString("mcc_gas_sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gas station.
        /// </summary>
        internal static string mcc_gas_station {
            get {
                return ResourceManager.GetString("mcc_gas_station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Contractors.
        /// </summary>
        internal static string mcc_general_contractors {
            get {
                return ResourceManager.GetString("mcc_general_contractors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Golf.
        /// </summary>
        internal static string mcc_golf {
            get {
                return ResourceManager.GetString("mcc_golf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goods.
        /// </summary>
        internal static string mcc_goods {
            get {
                return ResourceManager.GetString("mcc_goods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goods by mail.
        /// </summary>
        internal static string mcc_goods_by_mail {
            get {
                return ResourceManager.GetString("mcc_goods_by_mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Government Owned Lottery.
        /// </summary>
        internal static string mcc_government_owned_lottery {
            get {
                return ResourceManager.GetString("mcc_government_owned_lottery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Government procurement.
        /// </summary>
        internal static string mcc_government_procurement {
            get {
                return ResourceManager.GetString("mcc_government_procurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Government Services.
        /// </summary>
        internal static string mcc_government_services {
            get {
                return ResourceManager.GetString("mcc_government_services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grocery.
        /// </summary>
        internal static string mcc_grocery {
            get {
                return ResourceManager.GetString("mcc_grocery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haberdashery.
        /// </summary>
        internal static string mcc_haberdashery {
            get {
                return ResourceManager.GetString("mcc_haberdashery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardware Stores.
        /// </summary>
        internal static string mcc_hardware_stores {
            get {
                return ResourceManager.GetString("mcc_hardware_stores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health and beauty.
        /// </summary>
        internal static string mcc_health_and_beauty {
            get {
                return ResourceManager.GetString("mcc_health_and_beauty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hearing Aids.
        /// </summary>
        internal static string mcc_hearing_aids {
            get {
                return ResourceManager.GetString("mcc_hearing_aids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heating, Plumbing, A/C.
        /// </summary>
        internal static string mcc_heating_plumbing_a_c {
            get {
                return ResourceManager.GetString("mcc_heating_plumbing_a_c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horse / Dog racing.
        /// </summary>
        internal static string mcc_horse_dog_racing {
            get {
                return ResourceManager.GetString("mcc_horse_dog_racing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horticultural and landscaping.
        /// </summary>
        internal static string mcc_horticultural_and_landscaping {
            get {
                return ResourceManager.GetString("mcc_horticultural_and_landscaping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hospitals.
        /// </summary>
        internal static string mcc_hospitals {
            get {
                return ResourceManager.GetString("mcc_hospitals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotels and resorts.
        /// </summary>
        internal static string mcc_hotels_and_resorts {
            get {
                return ResourceManager.GetString("mcc_hotels_and_resorts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Household appliance.
        /// </summary>
        internal static string mcc_household_appliance {
            get {
                return ResourceManager.GetString("mcc_household_appliance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Household products.
        /// </summary>
        internal static string mcc_household_products {
            get {
                return ResourceManager.GetString("mcc_household_products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HVAC equipment repair.
        /// </summary>
        internal static string mcc_hvac_equipment_repair {
            get {
                return ResourceManager.GetString("mcc_hvac_equipment_repair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I-Purchasing Pilot.
        /// </summary>
        internal static string mcc_i_purchasing_pilot {
            get {
                return ResourceManager.GetString("mcc_i_purchasing_pilot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In-company purchases.
        /// </summary>
        internal static string mcc_in_company_purchases {
            get {
                return ResourceManager.GetString("mcc_in_company_purchases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industry.
        /// </summary>
        internal static string mcc_industry {
            get {
                return ResourceManager.GetString("mcc_industry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information Services.
        /// </summary>
        internal static string mcc_information_services {
            get {
                return ResourceManager.GetString("mcc_information_services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance.
        /// </summary>
        internal static string mcc_insurance {
            get {
                return ResourceManager.GetString("mcc_insurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jewelry.
        /// </summary>
        internal static string mcc_jewelry {
            get {
                return ResourceManager.GetString("mcc_jewelry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kindergarten.
        /// </summary>
        internal static string mcc_kindergarten {
            get {
                return ResourceManager.GetString("mcc_kindergarten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laundry.
        /// </summary>
        internal static string mcc_laundry {
            get {
                return ResourceManager.GetString("mcc_laundry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lawyers.
        /// </summary>
        internal static string mcc_lawyers {
            get {
                return ResourceManager.GetString("mcc_lawyers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leather Products.
        /// </summary>
        internal static string mcc_leather_products {
            get {
                return ResourceManager.GetString("mcc_leather_products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail.
        /// </summary>
        internal static string mcc_mail {
            get {
                return ResourceManager.GetString("mcc_mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance stations.
        /// </summary>
        internal static string mcc_maintenance_stations {
            get {
                return ResourceManager.GetString("mcc_maintenance_stations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketplaces.
        /// </summary>
        internal static string mcc_marketplaces {
            get {
                return ResourceManager.GetString("mcc_marketplaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masonry, Stonework, and Plaster.
        /// </summary>
        internal static string mcc_masonry_stonework_and_plaster {
            get {
                return ResourceManager.GetString("mcc_masonry_stonework_and_plaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Massage.
        /// </summary>
        internal static string mcc_massage {
            get {
                return ResourceManager.GetString("mcc_massage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meat.
        /// </summary>
        internal static string mcc_meat {
            get {
                return ResourceManager.GetString("mcc_meat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical equipment.
        /// </summary>
        internal static string mcc_medical_equipment {
            get {
                return ResourceManager.GetString("mcc_medical_equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical services.
        /// </summary>
        internal static string mcc_medical_services {
            get {
                return ResourceManager.GetString("mcc_medical_services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicine.
        /// </summary>
        internal static string mcc_medicine {
            get {
                return ResourceManager.GetString("mcc_medicine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicine and dentistry.
        /// </summary>
        internal static string mcc_medicine_and_dentistry {
            get {
                return ResourceManager.GetString("mcc_medicine_and_dentistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mens clothing.
        /// </summary>
        internal static string mcc_mens_clothing {
            get {
                return ResourceManager.GetString("mcc_mens_clothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchandise stores.
        /// </summary>
        internal static string mcc_merchandise_stores {
            get {
                return ResourceManager.GetString("mcc_merchandise_stores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metal processing.
        /// </summary>
        internal static string mcc_metal_processing {
            get {
                return ResourceManager.GetString("mcc_metal_processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous.
        /// </summary>
        internal static string mcc_miscellaneous {
            get {
                return ResourceManager.GetString("mcc_miscellaneous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous Publishing and Printing.
        /// </summary>
        internal static string mcc_miscellaneous_publishing_and_printing {
            get {
                return ResourceManager.GetString("mcc_miscellaneous_publishing_and_printing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile connection.
        /// </summary>
        internal static string mcc_mobile_connection {
            get {
                return ResourceManager.GetString("mcc_mobile_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile homes.
        /// </summary>
        internal static string mcc_mobile_homes {
            get {
                return ResourceManager.GetString("mcc_mobile_homes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money transfer.
        /// </summary>
        internal static string mcc_money_transfer {
            get {
                return ResourceManager.GetString("mcc_money_transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music bands. Orchestras.
        /// </summary>
        internal static string mcc_music_bands_orchestras {
            get {
                return ResourceManager.GetString("mcc_music_bands_orchestras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musical Instruments.
        /// </summary>
        internal static string mcc_musical_instruments {
            get {
                return ResourceManager.GetString("mcc_musical_instruments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newspapers. Magazines.
        /// </summary>
        internal static string mcc_newspapers_magazines {
            get {
                return ResourceManager.GetString("mcc_newspapers_magazines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;MCC&gt;.
        /// </summary>
        internal static string mcc_none {
            get {
                return ResourceManager.GetString("mcc_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office equipment.
        /// </summary>
        internal static string mcc_office_equipment {
            get {
                return ResourceManager.GetString("mcc_office_equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online casino.
        /// </summary>
        internal static string mcc_online_casino {
            get {
                return ResourceManager.GetString("mcc_online_casino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optics.
        /// </summary>
        internal static string mcc_optics {
            get {
                return ResourceManager.GetString("mcc_optics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizations, Membership.
        /// </summary>
        internal static string mcc_organizations_membership {
            get {
                return ResourceManager.GetString("mcc_organizations_membership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizations, Political.
        /// </summary>
        internal static string mcc_organizations_political {
            get {
                return ResourceManager.GetString("mcc_organizations_political", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizations, Religious.
        /// </summary>
        internal static string mcc_organizations_religious {
            get {
                return ResourceManager.GetString("mcc_organizations_religious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paints.
        /// </summary>
        internal static string mcc_paints {
            get {
                return ResourceManager.GetString("mcc_paints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parking.
        /// </summary>
        internal static string mcc_parking {
            get {
                return ResourceManager.GetString("mcc_parking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passenger railways.
        /// </summary>
        internal static string mcc_passenger_railways {
            get {
                return ResourceManager.GetString("mcc_passenger_railways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passenger transportation.
        /// </summary>
        internal static string mcc_passenger_transportation {
            get {
                return ResourceManager.GetString("mcc_passenger_transportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pawn Shops.
        /// </summary>
        internal static string mcc_pawn_shops {
            get {
                return ResourceManager.GetString("mcc_pawn_shops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payouts. Bonds.
        /// </summary>
        internal static string mcc_payouts_bonds {
            get {
                return ResourceManager.GetString("mcc_payouts_bonds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pet supplies.
        /// </summary>
        internal static string mcc_pet_supplies {
            get {
                return ResourceManager.GetString("mcc_pet_supplies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petroleum.
        /// </summary>
        internal static string mcc_petroleum {
            get {
                return ResourceManager.GetString("mcc_petroleum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Philatelicism.
        /// </summary>
        internal static string mcc_philatelicism {
            get {
                return ResourceManager.GetString("mcc_philatelicism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo goods.
        /// </summary>
        internal static string mcc_photo_goods {
            get {
                return ResourceManager.GetString("mcc_photo_goods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo printing.
        /// </summary>
        internal static string mcc_photo_printing {
            get {
                return ResourceManager.GetString("mcc_photo_printing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photographic Studios.
        /// </summary>
        internal static string mcc_photographic_studios {
            get {
                return ResourceManager.GetString("mcc_photographic_studios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photography and art.
        /// </summary>
        internal static string mcc_photography_and_art {
            get {
                return ResourceManager.GetString("mcc_photography_and_art", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plumbing.
        /// </summary>
        internal static string mcc_plumbing {
            get {
                return ResourceManager.GetString("mcc_plumbing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podiatrists.
        /// </summary>
        internal static string mcc_podiatrists {
            get {
                return ResourceManager.GetString("mcc_podiatrists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printing machines.
        /// </summary>
        internal static string mcc_printing_machines {
            get {
                return ResourceManager.GetString("mcc_printing_machines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professional services.
        /// </summary>
        internal static string mcc_professional_services {
            get {
                return ResourceManager.GetString("mcc_professional_services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programming.
        /// </summary>
        internal static string mcc_programming {
            get {
                return ResourceManager.GetString("mcc_programming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prostheses.
        /// </summary>
        internal static string mcc_prostheses {
            get {
                return ResourceManager.GetString("mcc_prostheses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public organizations.
        /// </summary>
        internal static string mcc_public_organizations {
            get {
                return ResourceManager.GetString("mcc_public_organizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quasi Cash.
        /// </summary>
        internal static string mcc_quasi_cash {
            get {
                return ResourceManager.GetString("mcc_quasi_cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Railway.
        /// </summary>
        internal static string mcc_railway {
            get {
                return ResourceManager.GetString("mcc_railway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razors.
        /// </summary>
        internal static string mcc_razors {
            get {
                return ResourceManager.GetString("mcc_razors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Shops.
        /// </summary>
        internal static string mcc_record_shops {
            get {
                return ResourceManager.GetString("mcc_record_shops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recreation.
        /// </summary>
        internal static string mcc_recreation {
            get {
                return ResourceManager.GetString("mcc_recreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renovation.
        /// </summary>
        internal static string mcc_renovation {
            get {
                return ResourceManager.GetString("mcc_renovation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rental Property.
        /// </summary>
        internal static string mcc_rental_property {
            get {
                return ResourceManager.GetString("mcc_rental_property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair of equipment.
        /// </summary>
        internal static string mcc_repair_of_equipment {
            get {
                return ResourceManager.GetString("mcc_repair_of_equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair of watches and jewelry.
        /// </summary>
        internal static string mcc_repair_of_watches_and_jewelry {
            get {
                return ResourceManager.GetString("mcc_repair_of_watches_and_jewelry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repairs.
        /// </summary>
        internal static string mcc_repairs {
            get {
                return ResourceManager.GetString("mcc_repairs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reproduction Stores.
        /// </summary>
        internal static string mcc_reproduction_stores {
            get {
                return ResourceManager.GetString("mcc_reproduction_stores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retail outlets with telephony.
        /// </summary>
        internal static string mcc_retail_outlets_with_telephony {
            get {
                return ResourceManager.GetString("mcc_retail_outlets_with_telephony", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retail stores.
        /// </summary>
        internal static string mcc_retail_stores {
            get {
                return ResourceManager.GetString("mcc_retail_stores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roofing/Siding, Sheet Metal.
        /// </summary>
        internal static string mcc_roofing_siding_sheet_metal {
            get {
                return ResourceManager.GetString("mcc_roofing_siding_sheet_metal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rubber stamp.
        /// </summary>
        internal static string mcc_rubber_stamp {
            get {
                return ResourceManager.GetString("mcc_rubber_stamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salesmen.
        /// </summary>
        internal static string mcc_salesmen {
            get {
                return ResourceManager.GetString("mcc_salesmen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School.
        /// </summary>
        internal static string mcc_school {
            get {
                return ResourceManager.GetString("mcc_school", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schools, Correspondence.
        /// </summary>
        internal static string mcc_schools_correspondence {
            get {
                return ResourceManager.GetString("mcc_schools_correspondence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Hand.
        /// </summary>
        internal static string mcc_second_hand {
            get {
                return ResourceManager.GetString("mcc_second_hand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Securities.
        /// </summary>
        internal static string mcc_securities {
            get {
                return ResourceManager.GetString("mcc_securities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Stations.
        /// </summary>
        internal static string mcc_service_stations {
            get {
                return ResourceManager.GetString("mcc_service_stations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sewing supplies.
        /// </summary>
        internal static string mcc_sewing_supplies {
            get {
                return ResourceManager.GetString("mcc_sewing_supplies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shoes.
        /// </summary>
        internal static string mcc_shoes {
            get {
                return ResourceManager.GetString("mcc_shoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping.
        /// </summary>
        internal static string mcc_shopping {
            get {
                return ResourceManager.GetString("mcc_shopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Souvenirs.
        /// </summary>
        internal static string mcc_souvenirs {
            get {
                return ResourceManager.GetString("mcc_souvenirs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Trade Contractors.
        /// </summary>
        internal static string mcc_special_trade_contractors {
            get {
                return ResourceManager.GetString("mcc_special_trade_contractors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialty Cleaning.
        /// </summary>
        internal static string mcc_specialty_cleaning {
            get {
                return ResourceManager.GetString("mcc_specialty_cleaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sports clubs.
        /// </summary>
        internal static string mcc_sports_clubs {
            get {
                return ResourceManager.GetString("mcc_sports_clubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sports goods.
        /// </summary>
        internal static string mcc_sports_goods {
            get {
                return ResourceManager.GetString("mcc_sports_goods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sportswear.
        /// </summary>
        internal static string mcc_sportswear {
            get {
                return ResourceManager.GetString("mcc_sportswear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stationery.
        /// </summary>
        internal static string mcc_stationery {
            get {
                return ResourceManager.GetString("mcc_stationery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stenography.
        /// </summary>
        internal static string mcc_stenography {
            get {
                return ResourceManager.GetString("mcc_stenography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage.
        /// </summary>
        internal static string mcc_storage {
            get {
                return ResourceManager.GetString("mcc_storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscriptions.
        /// </summary>
        internal static string mcc_subscriptions {
            get {
                return ResourceManager.GetString("mcc_subscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sweets.
        /// </summary>
        internal static string mcc_sweets {
            get {
                return ResourceManager.GetString("mcc_sweets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swimming Pools.
        /// </summary>
        internal static string mcc_swimming_pools {
            get {
                return ResourceManager.GetString("mcc_swimming_pools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxes.
        /// </summary>
        internal static string mcc_taxes {
            get {
                return ResourceManager.GetString("mcc_taxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxi.
        /// </summary>
        internal static string mcc_taxi {
            get {
                return ResourceManager.GetString("mcc_taxi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telecommunication equipment.
        /// </summary>
        internal static string mcc_telecommunication_equipment {
            get {
                return ResourceManager.GetString("mcc_telecommunication_equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegraph.
        /// </summary>
        internal static string mcc_telegraph {
            get {
                return ResourceManager.GetString("mcc_telegraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telemarketing.
        /// </summary>
        internal static string mcc_telemarketing {
            get {
                return ResourceManager.GetString("mcc_telemarketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone services.
        /// </summary>
        internal static string mcc_telephone_services {
            get {
                return ResourceManager.GetString("mcc_telephone_services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tents.
        /// </summary>
        internal static string mcc_tents {
            get {
                return ResourceManager.GetString("mcc_tents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing laboratories.
        /// </summary>
        internal static string mcc_testing_laboratories {
            get {
                return ResourceManager.GetString("mcc_testing_laboratories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The beauty.
        /// </summary>
        internal static string mcc_the_beauty {
            get {
                return ResourceManager.GetString("mcc_the_beauty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The television.
        /// </summary>
        internal static string mcc_the_television {
            get {
                return ResourceManager.GetString("mcc_the_television", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets.
        /// </summary>
        internal static string mcc_tickets {
            get {
                return ResourceManager.GetString("mcc_tickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeshares.
        /// </summary>
        internal static string mcc_timeshares {
            get {
                return ResourceManager.GetString("mcc_timeshares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tire service.
        /// </summary>
        internal static string mcc_tire_service {
            get {
                return ResourceManager.GetString("mcc_tire_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tires.
        /// </summary>
        internal static string mcc_tires {
            get {
                return ResourceManager.GetString("mcc_tires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tobacco products.
        /// </summary>
        internal static string mcc_tobacco_products {
            get {
                return ResourceManager.GetString("mcc_tobacco_products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toll roads.
        /// </summary>
        internal static string mcc_toll_roads {
            get {
                return ResourceManager.GetString("mcc_toll_roads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour operators.
        /// </summary>
        internal static string mcc_tour_operators {
            get {
                return ResourceManager.GetString("mcc_tour_operators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tourism.
        /// </summary>
        internal static string mcc_tourism {
            get {
                return ResourceManager.GetString("mcc_tourism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tow truck.
        /// </summary>
        internal static string mcc_tow_truck {
            get {
                return ResourceManager.GetString("mcc_tow_truck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toys.
        /// </summary>
        internal static string mcc_toys {
            get {
                return ResourceManager.GetString("mcc_toys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transportation. Bus.
        /// </summary>
        internal static string mcc_transportation_bus {
            get {
                return ResourceManager.GetString("mcc_transportation_bus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transportation. Delivery.
        /// </summary>
        internal static string mcc_transportation_delivery {
            get {
                return ResourceManager.GetString("mcc_transportation_delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transportation Services.
        /// </summary>
        internal static string mcc_transportation_services {
            get {
                return ResourceManager.GetString("mcc_transportation_services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travels.
        /// </summary>
        internal static string mcc_travels {
            get {
                return ResourceManager.GetString("mcc_travels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truck Rental.
        /// </summary>
        internal static string mcc_truck_rental {
            get {
                return ResourceManager.GetString("mcc_truck_rental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typesetting, Plate Making.
        /// </summary>
        internal static string mcc_typesetting_plate_making {
            get {
                return ResourceManager.GetString("mcc_typesetting_plate_making", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilities.
        /// </summary>
        internal static string mcc_utilities {
            get {
                return ResourceManager.GetString("mcc_utilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variety stores.
        /// </summary>
        internal static string mcc_variety_stores {
            get {
                return ResourceManager.GetString("mcc_variety_stores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veterinary Services.
        /// </summary>
        internal static string mcc_veterinary_services {
            get {
                return ResourceManager.GetString("mcc_veterinary_services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video rental.
        /// </summary>
        internal static string mcc_video_rental {
            get {
                return ResourceManager.GetString("mcc_video_rental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videogames.
        /// </summary>
        internal static string mcc_videogames {
            get {
                return ResourceManager.GetString("mcc_videogames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VISA.
        /// </summary>
        internal static string mcc_visa {
            get {
                return ResourceManager.GetString("mcc_visa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welding works.
        /// </summary>
        internal static string mcc_welding_works {
            get {
                return ResourceManager.GetString("mcc_welding_works", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wholesalers.
        /// </summary>
        internal static string mcc_wholesalers {
            get {
                return ResourceManager.GetString("mcc_wholesalers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wigs.
        /// </summary>
        internal static string mcc_wigs {
            get {
                return ResourceManager.GetString("mcc_wigs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wine producers.
        /// </summary>
        internal static string mcc_wine_producers {
            get {
                return ResourceManager.GetString("mcc_wine_producers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Womens clothing.
        /// </summary>
        internal static string mcc_womens_clothing {
            get {
                return ResourceManager.GetString("mcc_womens_clothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yachting service.
        /// </summary>
        internal static string mcc_yachting_service {
            get {
                return ResourceManager.GetString("mcc_yachting_service", resourceCulture);
            }
        }
    }
}
